<template>
  <section>
    <div class="row bg-primary">
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
    </div>
    <div class="row bg-success">
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
    </div>
    <div class="row bg-danger">
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
      <div class="col-4">
        <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis consequatur dolorum fugit nobis non odio optio quis ratione sit? Consequatur cumque delectus dolor excepturi facere id, itaque laboriosam, laudantium libero maiores molestiae nobis nostrum omnis pariatur placeat possimus qui recusandae reprehenderit ullam vitae? Inventore maxime totam vel voluptatem! Autem dolorem eligendi harum illum in modi nam natus odio saepe sit? Excepturi nam, veniam. At blanditiis cupiditate doloribus eligendi esse, eveniet expedita laborum minima mollitia nulla, numquam quo, reprehenderit! Accusantium adipisci consequatur debitis omnis qui sint tempora? Assumenda dolorem doloribus ea harum incidunt ipsum natus quibusdam quis temporibus voluptatibus. Accusamus aliquam blanditiis commodi consectetur cum deserunt error est ex expedita, iste laboriosam libero minima minus modi odio officia pariatur quasi quidem quo reiciendis suscipit tempore velit veritatis! Architecto autem consequatur consequuntur culpa dolorem doloribus earum eius eum illum ipsum iure laudantium magni molestiae neque nesciunt, numquam possimus quia quidem quis quod reprehenderit sapiente sequi sint totam voluptas? Aliquam dolor ea, laboriosam nisi non quidem reprehenderit? Iste libero, obcaecati. Maiores quas, saepe! Accusamus alias consequatur expedita explicabo fugit sit soluta totam! Alias at consectetur consequatur eum eveniet, ex exercitationem ipsum iure iusto laboriosam laborum odit officiis perferendis porro provident quasi quod similique tempora unde veniam? A animi aspernatur aut commodi doloremque eveniet excepturi ipsa obcaecati officia possimus provident quaerat sed sit sunt, suscipit ullam voluptates voluptatibus. Fuga fugiat quibusdam quod. Amet, eligendi est magni non obcaecati perferendis vel voluptates. Animi, corporis impedit ipsa ipsam obcaecati ratione sequi soluta veritatis. Accusantium alias atque deleniti ex incidunt ipsa ipsam iure necessitatibus quos rem! Animi eius inventore necessitatibus numquam? A aut autem, cumque cupiditate deleniti distinctio dolor dolores, ducimus earum enim eveniet explicabo id illo illum ipsam iste laboriosam molestiae nam neque nisi nobis perspiciatis, quasi quia ratione temporibus totam velit veritatis! Laudantium, perspiciatis.
        </p>
      </div>
    </div>
  </section>
</template>


<style lang="scss">



</style>
